[package]
name = "tmenu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.24.0"
freedesktop_entry_parser = "1.3.0"
tui = "0.18.0"
unicode-width = "0.1.9"
