[env]
BIN_NAME="tmenu"
COMPILER_FLAGS="--release"
INSTALL_PREFIX="/usr/bin"

[build]
cmd = """
cargo build $COMPILER_FLAGS &&
cp -r ./target/release/$BIN_NAME ./bin/$BIN_NAME
"""

[[custom]]
name = "clean"
cmd = "cargo clean"
run = false

[[custom]]
name = "setup"
cmd = """
mkdir -p bin &&
rustup install stable &&
rustup default stable
"""
run = false

[[custom]]
name = "install"
cmd = "cp ./bin/$BIN_NAME $INSTALL_PREFIX/$BIN_NAME"
run = false

[[custom]]
name = "uninstall"
cmd = "rm -rf $INSTALL_PREFIX/$BIN_NAME"
run = false

[[pre]]
name = "fmt"
cmd = "cargo fmt"
